services:

  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/workspace:cached
    networks:
      - backend
    

  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    command: ["--mysql-native-password=ON"]
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    #  - ./mysql-data:/var/lib/mysql
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
    #  - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  mysql-data:

networks:
    backend:
