services:

  web:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 5000:5000
    networks:
      - backend

  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    command: ["--mysql-native-password=ON"]
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    #  - ./mysql-data:/var/lib/mysql
      - ../mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ###
    networks:
      - backend

#volumes:
#  mysql-data:

networks:
    backend: